=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/SVS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:ihe:iti:svs:2008" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:hl7="urn:hl7-org:v3"
	targetNamespace="urn:ihe:iti:svs:2008" elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<xs:include schemaLocation="../processable/coreschemas/datatypes-base.xsd"/>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:simpleType name="valueSetIdType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-2](\.(0|[1-9][0-9]*))*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ConceptListType">
		<xs:sequence>
			<xs:element name="Concept" minOccurs="1" maxOccurs="unbounded" type="CD"/>
		</xs:sequence>
		<xs:attribute ref="xml:lang" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ValueSetType" abstract="true">
		<xs:attribute name="id" type="valueSetIdType" use="required"/>
		<xs:attribute name="version" use="optional" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="ValueSetRequestType">
		<xs:complexContent>
			<xs:extension base="ValueSetType">
				<xs:attribute ref="xml:lang" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ValueSetExtendedType" abstract="true">
		<xs:complexContent>
			<xs:extension base="ValueSetType">
				<xs:sequence>
					<xs:element name="ConceptList" type="ConceptListType" minOccurs="1"
						maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="displayName" use="optional" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ValueSetResponseType">
		<xs:complexContent>
			<xs:restriction base="ValueSetExtendedType">
				<xs:sequence>
					<xs:element name="ConceptList" type="ConceptListType" minOccurs="1"
						maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="id" type="valueSetIdType" use="required"/>
				<xs:attribute name="displayName" use="required" type="xs:string"/>
				<xs:attribute name="version" use="optional" type="xs:string"/>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RetrieveValueSetRequestType">
		<xs:sequence>
			<xs:element name="ValueSet" minOccurs="1" maxOccurs="1" type="ValueSetRequestType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RetrieveValueSetResponseType">
		<xs:sequence>
			<xs:element name="ValueSet" minOccurs="1" maxOccurs="1" type="ValueSetResponseType"/>
		</xs:sequence>
		<xs:attribute name="cacheExpirationHint" use="optional" type="xs:dateTime"/>
	</xs:complexType>
	<xs:element name="RetrieveValueSetRequest" type="RetrieveValueSetRequestType"/>
	<xs:element name="RetrieveValueSetResponse" type="RetrieveValueSetResponseType"/>
</xs:schema>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_Ovaire-Type-histologique-lesion-neoplasique-maligne-invasive-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.354" displayName="JDV_Ovaire-Type-histologique-lesion-neoplasique-maligne-invasive-CISIS" version="test"><ConceptList><Concept code="602" displayName="Tumeur épithéliale séreuse borderline" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="603" displayName="Adenocarcinome séreux" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="604" displayName="Tumeur épithéliale mucineuse" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="605" displayName="Adénocarcinome mucineux" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="606" displayName="Tumeur épithéliale endométrioïde borderline" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="607" displayName="Adénocarcinome endometrioide" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="608" displayName="Tumeur épithéliale à cellules claires borderline" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="609" displayName="Carcinome à cellules claires" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="610" displayName="Tumeur épithéliale à cellules transitionnelles borderline (tumeur de Brenner)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="611" displayName="Carcinome à cellules transitionnelles" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="612" displayName="Tumeur épithéliale carcinome indifférencié" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="613" displayName="Tumeur épithéliale autre" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="614" displayName="Tumeur de Sertoli Leydig" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="615" displayName="Tumeur de la granulosa adulte" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="616" displayName="Tumeur de la granulosa juvénile" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="617" displayName="Tumeur du stroma et des cordons sexuels autre" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="618" displayName="Tumeur germinale : préciser" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="619" displayName="Fibrosarcome" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_Corps-uterin-pT-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.267" displayName="JDV_Corps-uterin-pT-CISIS" version="test"><ConceptList><Concept code="585" displayName="pT0 [--]: No evidence of primary tumor" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="586" displayName="pT1a [IA]: Tumor limited to endometrium or invades less than one-half of the myometrium" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="587" displayName="pT1b [IB]: Tumor invades greater than or equal to one-half of the myometrium" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="588" displayName="pT2 [II]: Tumor invades stromal connective tissue of the cervix, but does not extend beyond uterus" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="589" displayName="pT3a [IIIA]: Tumor involves serosa and/or adnexa (direct extension or metastasis)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="590" displayName="pT3b [IIIB]: Vaginal involvement (direct extension or metastasis) or parametrial involvement" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="591" displayName="pT4 [IVA]: Tumor invades bladder mucosa and/or bowel mucosa (bullous edema is not sufficient to classify a tumor as T4)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_HL7_ActPriority-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="2.16.840.1.113883.5.7" displayName="JDV_HL7_ActPriority-CISIS" version="test"><ConceptList><Concept code="A" displayName="Aussi vite que possible" codeSystem="2.16.840.1.113883.5.7" dateValid="20100101000000" dateFin=""/><Concept code="EL" displayName="Bénéfique pour le patient mais pas essentiel pour sa survie" codeSystem="2.16.840.1.113883.5.7" dateValid="20100101000000" dateFin=""/><Concept code="EM" displayName="Très urgent" codeSystem="2.16.840.1.113883.5.7" dateValid="20100101000000" dateFin=""/><Concept code="P" displayName="A réaliser avant l'intervention" codeSystem="2.16.840.1.113883.5.7" dateValid="20100101000000" dateFin=""/><Concept code="PRN" displayName="Si nécessaire" codeSystem="2.16.840.1.113883.5.7" dateValid="20100101000000" dateFin=""/><Concept code="R" displayName="A réaliser aux heures ouvrées" codeSystem="2.16.840.1.113883.5.7" dateValid="20100101000000" dateFin=""/><Concept code="S" displayName="Immédiatement" codeSystem="2.16.840.1.113883.5.7" dateValid="20100101000000" dateFin=""/><Concept code="T" displayName="Plannification à respecter" codeSystem="2.16.840.1.113883.5.7" dateValid="20100101000000" dateFin=""/><Concept code="UR" displayName="Urgent" codeSystem="2.16.840.1.113883.5.7" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_HL7_HumanSubstanceAdministrationSite-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="2.16.840.1.113883.1.11.19724" displayName="JDV_HL7_HumanSubstanceAdministrationSite-CISIS" version="test"><ConceptList><Concept code="BE" displayName="dans les deux oreilles" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="BN" displayName="dans les deux narines" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="BU" displayName="fesse" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LA" displayName="bras gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LAC" displayName="poitrine antérieure gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LACF" displayName="région cubitale antérieure gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LD" displayName="deltoïde gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LE" displayName="oreille gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LEJ" displayName="jugulaire externe gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LF" displayName="pied gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LG" displayName="muscle moyen fessier gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LH" displayName="main gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LIJ" displayName="jugulaire interne gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LLAQ" displayName="quadrant inférieur gauche de l'abdomen" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LLFA" displayName="avant-bras inférieur gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LMFA" displayName="avant-bras moyen gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LN" displayName="narine gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LPC" displayName="poitrine postérieure gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LSC" displayName="sous-clavière gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LT" displayName="cuisse gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LUA" displayName="bras supérieur gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LUAQ" displayName="quadrant supérieur gauche de l'abdomen" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LUFA" displayName="avant-bras supérieur gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LVG" displayName="muscle fessier antérieur gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="LVL" displayName="muscle vaste externe gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="OD" displayName="oeil droit" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="OS" displayName="oeil gauche" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="OU" displayName="dans les deux yeux" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="PA" displayName="péri-anal" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="PERIN" displayName="périnéal" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RA" displayName="bras droit" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RAC" displayName="poitrine antérieure droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RACF" displayName="région cubitale antérieure droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RD" displayName="deltoïde droit" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RE" displayName="oreille droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="REJ" displayName="jugulaire externe droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RF" displayName="pied droit" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RG" displayName="muscle moyen fessier droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RH" displayName="main droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RIJ" displayName="jugulaire interne droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RLAQ" displayName="quadrant inférieur droit de l'abdomen" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RLFA" displayName="avant-bras inférieur droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RMFA" displayName="avant-bras moyen droit" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RN" displayName="narine droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RPC" displayName="poitrine postérieure droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RSC" displayName="sous-clavière droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RT" displayName="cuisse droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RUA" displayName="bras supérieur droit" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RUAQ" displayName="quadrant supérieur droit de l'abdomen" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RUFA" displayName="avant-bras supérieur droite" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RVG" displayName="muscle fessier antérieur droit" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/><Concept code="RVL" displayName="muscle vaste externe droit" codeSystem="2.16.840.1.113883.5.1052" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_ExamenMicroscopiqueTumeurTypeHistologique_CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.541" displayName="JDV_ExamenMicroscopiqueTumeurTypeHistologique_CISIS" version="test"><ConceptList><Concept code="C2852" displayName="Adénocarcinome (sans aspect histologique particulier)" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/><Concept code="C26712" displayName="Adénocarcinome mucineux" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/><Concept code="C3774" displayName="Carcinome à cellules en bague à chaton" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/><Concept code="C8998" displayName="Carcinome médullaire" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/><Concept code="MED-708" displayName="Adénocarcinome festonné" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="C96491" displayName="Adénocarcinome micropapillaire" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/><Concept code="C172699" displayName="Adénocarcinome &quot;adenoma-like&quot;" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/><Concept code="C3727" displayName="Carcinome adénosquameux" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/><Concept code="C96494" displayName="Carcinome avec composante sarcomatoïde" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/><Concept code="C3692" displayName="Carcinome indifférencié" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/><Concept code="MED-714" displayName="Autre carcinome" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="MED-715" displayName="TNE / TNE et non NE" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="MED-716" displayName="Tumeur lymphoïde" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="C3868" displayName="GIST" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/><Concept code="MED-718" displayName="Tumeur mésenchymateuse (hors GIST)" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="C19151" displayName="Métastase" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_TypeActeEUVN-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.228" displayName="JDV_TypeActeEUVN-CISIS" version="test"><ConceptList><Concept code="P1-30330" displayName="Endartériectomie" codeSystem="1.2.250.1.213.2.12" dateValid="20100101000000" dateFin=""/><Concept code="P1-30800" displayName="Angioplastie" codeSystem="1.2.250.1.213.2.12" dateValid="20100101000000" dateFin=""/><Concept code="P1-91300" displayName="Crâniectomie" codeSystem="1.2.250.1.213.2.12" dateValid="20100101000000" dateFin=""/><Concept code="P1-91221" displayName="Evacuation hématome intracérébral" codeSystem="1.2.250.1.213.2.12" dateValid="20100101000000" dateFin=""/><Concept code="MED-512" displayName="Pose Valve / Dérivation externe" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_NIHSSFonction-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.178" displayName="JDV_NIHSSFonction-CISIS" version="test"><ConceptList><Concept code="70184-7" displayName="Niveau conscience [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70185-4" displayName="LOC Questions [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70186-2" displayName="LOC Commandes [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70187-0" displayName="Occulomotricité [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70188-8" displayName="Champ visuel [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70189-6" displayName="Paralysie faciale [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70967-5" displayName="motricité MSD [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70190-4" displayName="motricité MSG [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70968-3" displayName="motricité MID [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70191-2" displayName="motricité MIG [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70192-0" displayName="Ataxie des membres [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70193-8" displayName="Sensibilité [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70194-6" displayName="Meilleur langage [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70195-3" displayName="Dysarthrie [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="70196-1" displayName="Extinction ou négligence [NIHSS]" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_NiveauEtude-CISIS.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Créé par nmahraz, le 09/03/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.108" displayName="JDV_NiveauEtude-CISIS" version="test"><ConceptList><Concept code="PAT-035" displayName="Ecole primaire" codeSystem="1.2.250.1.213.1.1.4.322"/><Concept code="PAT-036" displayName="Collège" codeSystem="1.2.250.1.213.1.1.4.322"/><Concept code="PAT-037" displayName="Lycée" codeSystem="1.2.250.1.213.1.1.4.322"/><Concept code="PAT-038" displayName="Bac +1 ou +2" codeSystem="1.2.250.1.213.1.1.4.322"/><Concept code="PAT-039" displayName="Bac +3 et +" codeSystem="1.2.250.1.213.1.1.4.322"/></ConceptList></ValueSet></RetrieveValueSetResponse>
