=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/SVS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:ihe:iti:svs:2008" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:hl7="urn:hl7-org:v3"
	targetNamespace="urn:ihe:iti:svs:2008" elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<xs:include schemaLocation="../processable/coreschemas/datatypes-base.xsd"/>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:simpleType name="valueSetIdType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-2](\.(0|[1-9][0-9]*))*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ConceptListType">
		<xs:sequence>
			<xs:element name="Concept" minOccurs="1" maxOccurs="unbounded" type="CD"/>
		</xs:sequence>
		<xs:attribute ref="xml:lang" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ValueSetType" abstract="true">
		<xs:attribute name="id" type="valueSetIdType" use="required"/>
		<xs:attribute name="version" use="optional" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="ValueSetRequestType">
		<xs:complexContent>
			<xs:extension base="ValueSetType">
				<xs:attribute ref="xml:lang" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ValueSetExtendedType" abstract="true">
		<xs:complexContent>
			<xs:extension base="ValueSetType">
				<xs:sequence>
					<xs:element name="ConceptList" type="ConceptListType" minOccurs="1"
						maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="displayName" use="optional" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ValueSetResponseType">
		<xs:complexContent>
			<xs:restriction base="ValueSetExtendedType">
				<xs:sequence>
					<xs:element name="ConceptList" type="ConceptListType" minOccurs="1"
						maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="id" type="valueSetIdType" use="required"/>
				<xs:attribute name="displayName" use="required" type="xs:string"/>
				<xs:attribute name="version" use="optional" type="xs:string"/>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RetrieveValueSetRequestType">
		<xs:sequence>
			<xs:element name="ValueSet" minOccurs="1" maxOccurs="1" type="ValueSetRequestType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RetrieveValueSetResponseType">
		<xs:sequence>
			<xs:element name="ValueSet" minOccurs="1" maxOccurs="1" type="ValueSetResponseType"/>
		</xs:sequence>
		<xs:attribute name="cacheExpirationHint" use="optional" type="xs:dateTime"/>
	</xs:complexType>
	<xs:element name="RetrieveValueSetRequest" type="RetrieveValueSetRequestType"/>
	<xs:element name="RetrieveValueSetResponse" type="RetrieveValueSetResponseType"/>
</xs:schema>

=== ansforge/TestContenuCDA-2-41/JDV_Pharynx-Observation-anatomie-pathologique-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.376" displayName="JDV_Pharynx-Observation-anatomie-pathologique-CISIS" version="test"><ConceptList><Concept code="335" displayName="Pharynx-Atteinte des limites de résection par la tumeur in situ" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="336" displayName="Pharynx-Atteinte des limites de résection par la tumeur maligne invasive" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="337" displayName="Pharynx-Distance tumeur in situ/plus proche limite de résection" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="338" displayName="Pharynx-Distance tumeur maligne invasive/plus proche limite de résection" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="339" displayName="Pharynx-Emboles vasculaires" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="340" displayName="Pharynx-Extension microscopique et macroscopique de la tumeur" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="341" displayName="Pharynx-Infiltration péri-nerveuse" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="342" displayName="Pharynx-Invasion de la capsule" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="343" displayName="Pharynx-Localisation de la tumeur dans l'organe" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="344" displayName="Pharynx-Localisation de(s) ganglion(s)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="345" displayName="Pharynx-Nombre de ganglion(s) envahi(s)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="346" displayName="Pharynx-Nombre de ganglion(s) examiné(s)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="347" displayName="Pharynx-Organe-region-prelevement-CISIS" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="348" displayName="Pharynx-pN carcinome hypoPharynx" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="349" displayName="Pharynx-pN carcinome nasoPharynx" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="350" displayName="Pharynx-pN mélanome muqueux malin" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="351" displayName="Pharynx-Procédure de prélèvement" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="352" displayName="Pharynx-pT carcinome hypoPharynx" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="353" displayName="Pharynx-pT carcinome nasoPharynx" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="354" displayName="Pharynx-pT mélanome muqueux malin" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="355" displayName="Pharynx-Taille de la métastase ganglionnaire" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="356" displayName="Pharynx-Taille de tumeur maligne invasive (plus grande dimension)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="357" displayName="Pharynx-Taille du prélèvement (plus grande dimension)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="358" displayName="Pharynx-Type-histologique-lesion-neoplasique-maligne-invasive-CISIS" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_MethodePreparationEchantillon-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.151" displayName="JDV_MethodePreparationEchantillon-CISIS" version="test"><ConceptList><Concept code="MED-302" displayName="Macro dissection de la zone d’intérêt" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="MED-303" displayName="Punch du bloc tumoral" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="MED-304" displayName="Production de copeaux de paraffines à partir du bloc tumoral" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="MED-305" displayName="Traitement de lames de cytologie" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="GEN-097" displayName="Autre (préciser)" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin="20220413000000"/><Concept code="GEN-092" displayName="Autre" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20220413000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_BatterieExamen-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.102" displayName="JDV_BatterieExamen-CISIS" version="test"><ConceptList><Concept code="GEN-078" displayName="Dépistage de la trisomie 21" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="ORG-079" displayName="Nombre total d'échographies" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="ORG-080" displayName="Echographie morphologique" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="51659-1" displayName="Hépatite B virus surface Ag" codeSystem="2.16.840.1.113883.6.1" dateValid="20100101000000" dateFin=""/><Concept code="GEN-079" displayName="Entretien prénatal précoce" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_Rein-Observation-anatomie-pathologique-CISIS.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Créé par nmahraz, le 09/03/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.411" displayName="JDV_Rein-Observation-anatomie-pathologique-CISIS" version="test"><ConceptList><Concept code="398" displayName="Rein-Atteinte des limites de résection par la tumeur maligne invasive" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="399" displayName="Rein-Distance tumeur maligne invasive/plus proche limite de résection" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="400" displayName="Rein-Emboles vasculaires" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="401" displayName="Rein-Extension microscopique et macroscopique de la tumeur" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="402" displayName="Rein-Grade histologique (Fuhrman)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="403" displayName="Rein-Localisation de la tumeur dans l'organe" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="404" displayName="Rein-Localisation de(s) limite(s) de résection" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="405" displayName="Rein-Nombre de ganglion(s) envahi(s)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="406" displayName="Rein-Nombre de ganglion(s) examiné(s)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="407" displayName="Rein-Organe-region-prelevement-CISIS" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="408" displayName="Rein-pN" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="409" displayName="Rein-Procédure de prélèvement" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="410" displayName="Rein-pT" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="411" displayName="Rein-Taille de tumeur maligne invasive (plus grande dimension)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/><Concept code="412" displayName="Rein-Type-histologique-lesion-neoplasique-maligne-invasive-CISIS" codeSystem="1.3.6.1.4.1.19376.1.8.2.1"/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_OBP_AspectLA-CISIS.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Créé par nmahraz, le 09/03/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.4.2.289.18" displayName="JDV_OBP_AspectLA-CISIS" version="test"><ConceptList><Concept code="G-A456" displayName="Clair" codeSystem="1.2.250.1.213.2.12"/><Concept code="OBS_216" displayName="Teinté (méconial fluide)" codeSystem="1.2.250.1.213.1.1.4.2.289"/><Concept code="OBS_217" displayName="Méconial épais" codeSystem="1.2.250.1.213.1.1.4.2.289"/><Concept code="OBS_218" displayName="Sanglant" codeSystem="1.2.250.1.213.1.1.4.2.289"/><Concept code="OBS_219" displayName="Autre aspect du liquide amniotique" codeSystem="1.2.250.1.213.1.1.4.2.289"/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_OBP_StaticSAPActiveProblem-CISIS.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Créé par nmahraz, le 09/03/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.4.2.289.46" displayName="JDV_OBP_StaticSAPActiveProblem-CISIS" version="test"><ConceptList><Concept code="D7-10030" displayName="Infection urinaire" codeSystem="1.2.250.1.213.2.12"/><Concept code="D8-11000" displayName="Hypertension artérielle" codeSystem="1.2.250.1.213.2.12"/><Concept code="D8-12000" displayName="Menace d'accouchement prématuré" codeSystem="1.2.250.1.213.2.12"/><Concept code="E14" displayName="Diabète" codeSystem="2.16.840.1.113883.6.3"/><Concept code="OBS_016" displayName="Métrorragies du 2ème- 3ème trimestre" codeSystem="1.2.250.1.213.1.1.4.2.289"/><Concept code="OBS_017" displayName="Rupture prématurée des membranes" codeSystem="1.2.250.1.213.1.1.4.2.289"/><Concept code="OBS_019" displayName="Autres pathologies maternelles" codeSystem="1.2.250.1.213.1.1.4.2.289"/><Concept code="OBS_132" displayName="Infection cervico-vaginale" codeSystem="1.2.250.1.213.1.1.4.2.289"/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_TNM_pTNM_pN_CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.551" displayName="JDV_TNM_pTNM_pN_CISIS" version="test"><ConceptList><Concept code="MED-795" displayName="Ganglions  lymphatiques régionaux non évaluables" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="MED-796" displayName="Pas de métastase ganglionnaire lymphatique régionale" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="MED-797" displayName="Métastase dans 1 ganglion lymphatique régional" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="MED-798" displayName="Métastases dans 2 ou 3 ganglions lymphatiques régionaux" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="MED-799" displayName="Présence de dépôt(s) tumoral(aux) sans métastase ganglionnaire lymphatique régionale" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="MED-800" displayName="Métastases dans 4 à 6 ganglions lymphatiques régionaux" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/><Concept code="MED-801" displayName="Métastases dans plus de 6 ganglions lymphatiques régionaux" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_TypePriseEnCharge-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.231" displayName="JDV_TypePriseEnCharge-CISIS" version="test"><ConceptList><Concept code="ORG-165" displayName="Séjour de répit" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="ORG-166" displayName="Maison d'accueil spécialisé (MAS) / Foyer d'accueil médicalisé (FAM)" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="ORG-167" displayName="Hospitalisation complète" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="ORG-072" displayName="Hospitalisation à domicile (HAD)" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="ORG-044" displayName="Hôpital de jour (HDJ)" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="ORG-168" displayName="Services de soins infirmiers à domicile (SSIAD)" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/><Concept code="GEN-092" displayName="Autre" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>
