=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/SVS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:ihe:iti:svs:2008" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:hl7="urn:hl7-org:v3"
	targetNamespace="urn:ihe:iti:svs:2008" elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<xs:include schemaLocation="../processable/coreschemas/datatypes-base.xsd"/>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:simpleType name="valueSetIdType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-2](\.(0|[1-9][0-9]*))*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ConceptListType">
		<xs:sequence>
			<xs:element name="Concept" minOccurs="1" maxOccurs="unbounded" type="CD"/>
		</xs:sequence>
		<xs:attribute ref="xml:lang" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ValueSetType" abstract="true">
		<xs:attribute name="id" type="valueSetIdType" use="required"/>
		<xs:attribute name="version" use="optional" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="ValueSetRequestType">
		<xs:complexContent>
			<xs:extension base="ValueSetType">
				<xs:attribute ref="xml:lang" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ValueSetExtendedType" abstract="true">
		<xs:complexContent>
			<xs:extension base="ValueSetType">
				<xs:sequence>
					<xs:element name="ConceptList" type="ConceptListType" minOccurs="1"
						maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="displayName" use="optional" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ValueSetResponseType">
		<xs:complexContent>
			<xs:restriction base="ValueSetExtendedType">
				<xs:sequence>
					<xs:element name="ConceptList" type="ConceptListType" minOccurs="1"
						maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="id" type="valueSetIdType" use="required"/>
				<xs:attribute name="displayName" use="required" type="xs:string"/>
				<xs:attribute name="version" use="optional" type="xs:string"/>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RetrieveValueSetRequestType">
		<xs:sequence>
			<xs:element name="ValueSet" minOccurs="1" maxOccurs="1" type="ValueSetRequestType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RetrieveValueSetResponseType">
		<xs:sequence>
			<xs:element name="ValueSet" minOccurs="1" maxOccurs="1" type="ValueSetResponseType"/>
		</xs:sequence>
		<xs:attribute name="cacheExpirationHint" use="optional" type="xs:dateTime"/>
	</xs:complexType>
	<xs:element name="RetrieveValueSetRequest" type="RetrieveValueSetRequestType"/>
	<xs:element name="RetrieveValueSetResponse" type="RetrieveValueSetResponseType"/>
</xs:schema>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_Lateralites-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.482" displayName="JDV_Lateralites-CISIS" version="test"><ConceptList><Concept code="LA4306-2" displayName="Droit" codeSystem="2.16.840.1.113883.6.1" dateValid="20200101000000" dateFin="20211231000000"/><Concept code="LA4585-1" displayName="Gauche" codeSystem="2.16.840.1.113883.6.1" dateValid="20200101000000" dateFin="20211231000000"/><Concept code="LA25377-5" displayName="Bilatéral" codeSystem="2.16.840.1.113883.6.1" dateValid="20200101000000" dateFin="20211231000000"/><Concept code="LA25378-3" displayName="Unilatéral" codeSystem="2.16.840.1.113883.6.1" dateValid="20200101000000" dateFin="20211231000000"/><Concept code="LA4720-4" displayName="Non applicable" codeSystem="2.16.840.1.113883.6.1" dateValid="20200101000000" dateFin="20211231000000"/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_MesureLentilleDelivree-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.656" displayName="JDV_MesureLentilleDelivree-CISIS" version="test"><ConceptList><Concept code="11778-8" displayName="Date De délivrance" codeSystem="2.16.840.1.113883.6.1" dateValid="20210924000000" dateFin=""/><Concept code="80418-7" displayName="Produit d'entretien" codeSystem="2.16.840.1.113883.6.1" dateValid="20210924000000" dateFin=""/><Concept code="28866-2" displayName="Type de lentille" codeSystem="2.16.840.1.113883.6.1" dateValid="20210924000000" dateFin=""/><Concept code="GEN-292" displayName="Commentaire" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210924000000" dateFin=""/><Concept code="C53610" displayName="Renouvellement" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210924000000" dateFin=""/><Concept code="C43383" displayName="Marque et Modèle" codeSystem="2.16.840.1.113883.3.26.1.1" dateValid="20210924000000" dateFin=""/><Concept code="MED-1089" displayName="Diamètre lentille – lentille délivrée" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210924000000" dateFin=""/><Concept code="MED-1090" displayName="Rayon 1 lentille – lentille délivrée" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210924000000" dateFin=""/><Concept code="MED-1091" displayName="Rayon 2 lentille – lentille délivrée" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210924000000" dateFin=""/><Concept code="MED-896" displayName="Autres paramètres" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210924000000" dateFin=""/><Concept code="MED-1092" displayName="Puissance de la sphère – lentille délivrée" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210924000000" dateFin=""/><Concept code="MED-1093" displayName="Puissance du cylindre – lentille délivrée" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210924000000" dateFin=""/><Concept code="95325-7" displayName="Axe en degrés des lentilles" codeSystem="2.16.840.1.113883.6.1" dateValid="20210924000000" dateFin=""/><Concept code="28814-2" displayName="Addition – grandeur" codeSystem="2.16.840.1.113883.6.1" dateValid="20210924000000" dateFin=""/><Concept code="28815-9" displayName="Addition – valeur" codeSystem="2.16.840.1.113883.6.1" dateValid="20210924000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_TypeService-CISIS.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Créé par nmahraz, le 09/03/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.127" displayName="JDV_TypeService-CISIS" version="test"><ConceptList><Concept code="ORG-139" displayName="Réanimation" codeSystem="1.2.250.1.213.1.1.4.322"/><Concept code="ORG-140" displayName="Néonatologie" codeSystem="1.2.250.1.213.1.1.4.322"/><Concept code="ORG-141" displayName="Unité Kangourou" codeSystem="1.2.250.1.213.1.1.4.322"/><Concept code="ORG-142" displayName="Unité de soin intensif en néonatalogie (USIN)" codeSystem="1.2.250.1.213.1.1.4.322"/><Concept code="GEN-097" displayName="Autre (préciser)" codeSystem="1.2.250.1.213.1.1.4.322"/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/JDV_OBP_LieuAccouchement-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.4.2.289.21" displayName="JDV_OBP_LieuAccouchement-CISIS" version="test"><ConceptList><Concept code="OBS_201" displayName="Maternité" codeSystem="1.2.250.1.213.1.1.4.2.289" dateValid="20100101000000" dateFin=""/><Concept code="OBS_202" displayName="Domicile" codeSystem="1.2.250.1.213.1.1.4.2.289" dateValid="20100101000000" dateFin=""/><Concept code="OBS_203" displayName="Autre maternité" codeSystem="1.2.250.1.213.1.1.4.2.289" dateValid="20100101000000" dateFin="20220413000000"/><Concept code="OBS_204" displayName="Autre lieu" codeSystem="1.2.250.1.213.1.1.4.2.289" dateValid="20100101000000" dateFin="20220413000000"/><Concept code="GEN-092" displayName="Autre" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20220413000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_UFCV_MotImpl-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.4.2.13" displayName="JDV_UFCV_MotImpl-CISIS" version="test"><ConceptList><Concept code="D0016-6" displayName="Prévention primaire d'un sujet à haut risque" codeSystem="1.2.250.1.213.1.1.4.2" dateValid="20100101000000" dateFin=""/><Concept code="G45.9" displayName="Accident ischémique cérébral transitoire" codeSystem="2.16.840.1.113883.6.3" dateValid="20100101000000" dateFin=""/><Concept code="I20.9" displayName="Syndrome Angineux" codeSystem="2.16.840.1.113883.6.3" dateValid="20100101000000" dateFin=""/><Concept code="I64" displayName="Accident cérébrovasculaire" codeSystem="2.16.840.1.113883.6.3" dateValid="20100101000000" dateFin=""/><Concept code="I65.2" displayName="Sténose de l'artère carotide" codeSystem="2.16.840.1.113883.6.3" dateValid="20100101000000" dateFin=""/><Concept code="I74.3" displayName="Thrombose progressive des artères des membres inférieurs" codeSystem="2.16.840.1.113883.6.3" dateValid="20100101000000" dateFin=""/><Concept code="I74.4" displayName="Embolie et thrombose des artères distales" codeSystem="2.16.840.1.113883.6.3" dateValid="20100101000000" dateFin=""/><Concept code="K55.0" displayName="Artérite Mésentérique" codeSystem="2.16.840.1.113883.6.3" dateValid="20100101000000" dateFin=""/><Concept code="N28.0" displayName="Occlusion et thrombose de l'artère rénale" codeSystem="2.16.840.1.113883.6.3" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_TypeDeMesureDispositifOculaire-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.643" displayName="JDV_TypeDeMesureDispositifOculaire-CISIS" version="test"><ConceptList><Concept code="28821-7" displayName="Verres prescrits" codeSystem="2.16.840.1.113883.6.1" dateValid="20210622000000" dateFin=""/><Concept code="28818-3" displayName="Types de verres prescrits" codeSystem="2.16.840.1.113883.6.1" dateValid="20210622000000" dateFin=""/><Concept code="MED-1067" displayName="Verres délivrés" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210622000000" dateFin=""/><Concept code="MED-1068" displayName="Types de verres délivrés" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210622000000" dateFin=""/><Concept code="28866-2" displayName="Lentilles prescrites" codeSystem="2.16.840.1.113883.6.1" dateValid="20210622000000" dateFin=""/><Concept code="MED-1069" displayName="Lentilles délivrées" codeSystem="1.2.250.1.213.1.1.4.322" dateValid="20210622000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_Col-Uterus-Type-histologique-lesion-neoplasique-in-situ-CISIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Créé par nmahraz, le 12/09/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.246" displayName="JDV_Col-Uterus-Type-histologique-lesion-neoplasique-in-situ-CISIS" version="test"><ConceptList><Concept code="1663" displayName="Néoplasie cervicale intra-épithéliale de haut grade (CIN3)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="1664" displayName="Néoplasie cervicale intra-épithéliale de grade intermédiaire (CIN2)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="1665" displayName="Néoplasie cervicale intra-épithéliale de bas grade (CIN1)" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="1666" displayName="Condylome acuminé ou plan" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="1667" displayName="Carcinome épidermoide in situ" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="1668" displayName="Dysplasie glandulaire, atypies des cellules glandulaires" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="1669" displayName="Adénocarcinome endocervical in situ" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>

=== ansforge/TestContenuCDA-2-41/jeuxDeValeurs/JDV_Prostate-Grade-histologique-Gleason-Composante-plus-pejorative-CISIS.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Créé par nmahraz, le 05/07/2022-->
<RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ihe:iti:svs:2008 SVS.xsd" xmlns="urn:ihe:iti:svs:2008"><ValueSet id="1.2.250.1.213.1.1.5.397" displayName="JDV_Prostate-Grade-histologique-Gleason-Composante-plus-pejorative-CISIS" version="test"><ConceptList><Concept code="1017" displayName="Grade 1" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="1018" displayName="Grade 2" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="1019" displayName="Grade 3" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="1020" displayName="Grade 4" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/><Concept code="1021" displayName="Grade 5" codeSystem="1.3.6.1.4.1.19376.1.8.2.1" dateValid="20100101000000" dateFin=""/></ConceptList></ValueSet></RetrieveValueSetResponse>
